// <auto-generated />
using System;
using MECWeb.DbModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MECWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250819145627_AddInstallationStatus")]
    partial class AddInstallationStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MECWeb.DbModels.Machine.DbMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("mec_machine");
                });

            modelBuilder.Entity("MECWeb.DbModels.Project.DbProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectNumber")
                        .IsUnique();

                    b.ToTable("mec_project");
                });

            modelBuilder.Entity("MECWeb.DbModels.Translate.DbTranslateDictionary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("mec_translate_dictionary");
                });

            modelBuilder.Entity("MECWeb.DbModels.Translate.DbTranslateEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DictionaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryId");

                    b.ToTable("mec_translate_entry");
                });

            modelBuilder.Entity("MECWeb.DbModels.Translate.DbTranslateProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalItemsCount")
                        .HasColumnType("int");

                    b.Property<int>("TranslatedItemsCount")
                        .HasColumnType("int");

                    b.Property<int>("TranslationFileType")
                        .HasColumnType("int");

                    b.Property<int>("TranslationService")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("mec_translate_project");
                });

            modelBuilder.Entity("MECWeb.DbModels.Translate.DbTranslateTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Value")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("mec_translate_translation");
                });

            modelBuilder.Entity("MECWeb.DbModels.User.DbUser", b =>
                {
                    b.Property<Guid>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UId");

                    b.ToTable("mec_user");
                });

            modelBuilder.Entity("MECWeb.DbModels.User.DbUserProject", b =>
                {
                    b.Property<Guid>("DbUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DbProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DbUserId", "DbProjectId");

                    b.HasIndex("DbProjectId");

                    b.ToTable("mec_user_project");
                });

            modelBuilder.Entity("MECWeb.DbModels.User.DbUserProjectFavorite", b =>
                {
                    b.Property<Guid>("DbUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DbProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DbUserId", "DbProjectId");

                    b.HasIndex("DbProjectId");

                    b.ToTable("mec_user_project_favorite");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbBvHardwareComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BvHardwareComputerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ComponentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("Quantity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BvHardwareComputerId");

                    b.ToTable("mec_bv_hardware_component");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbBvHardwareComputer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PcTypeDetails")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("mec_bv_hardware_computer");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbConfigurationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BvHardwareComputerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SoftwareComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BvHardwareComputerId");

                    b.HasIndex("SoftwareComponentId");

                    b.ToTable("mec_configuration_entry");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbHardwareComputer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HardwareSpecs")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("mec_hardware_computer");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbHardwareField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FieldValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("HardwareComputerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidationRules")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("HardwareComputerId");

                    b.ToTable("mec_hardware_field");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbSoftwareComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComponentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConfigurationPath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("HardwareComputerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsConfigured")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HardwareComputerId");

                    b.ToTable("mec_software_component");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("mec_workflow");
                });

            modelBuilder.Entity("MECWeb.DbModels.Machine.DbMachine", b =>
                {
                    b.HasOne("MECWeb.DbModels.Project.DbProject", "Project")
                        .WithMany("Machines")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MECWeb.DbModels.Translate.DbTranslateEntry", b =>
                {
                    b.HasOne("MECWeb.DbModels.Translate.DbTranslateDictionary", "Dictionary")
                        .WithMany("Entries")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");
                });

            modelBuilder.Entity("MECWeb.DbModels.Translate.DbTranslateProject", b =>
                {
                    b.HasOne("MECWeb.DbModels.Project.DbProject", "Project")
                        .WithMany("TranslateProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MECWeb.DbModels.Translate.DbTranslateTranslation", b =>
                {
                    b.HasOne("MECWeb.DbModels.Translate.DbTranslateEntry", "Entry")
                        .WithMany("Translations")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("MECWeb.DbModels.User.DbUserProject", b =>
                {
                    b.HasOne("MECWeb.DbModels.Project.DbProject", "Project")
                        .WithMany("UserProjects")
                        .HasForeignKey("DbProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MECWeb.DbModels.User.DbUser", "User")
                        .WithMany("UserProjects")
                        .HasForeignKey("DbUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MECWeb.DbModels.User.DbUserProjectFavorite", b =>
                {
                    b.HasOne("MECWeb.DbModels.Project.DbProject", "Project")
                        .WithMany("UserProjectFavorites")
                        .HasForeignKey("DbProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MECWeb.DbModels.User.DbUser", "User")
                        .WithMany("UserProjectFavorites")
                        .HasForeignKey("DbUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbBvHardwareComponent", b =>
                {
                    b.HasOne("MECWeb.DbModels.Workflow.DbBvHardwareComputer", "BvHardwareComputer")
                        .WithMany("HardwareComponents")
                        .HasForeignKey("BvHardwareComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BvHardwareComputer");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbBvHardwareComputer", b =>
                {
                    b.HasOne("MECWeb.DbModels.Workflow.DbWorkflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbConfigurationEntry", b =>
                {
                    b.HasOne("MECWeb.DbModels.Workflow.DbBvHardwareComputer", "BvHardwareComputer")
                        .WithMany()
                        .HasForeignKey("BvHardwareComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MECWeb.DbModels.Workflow.DbSoftwareComponent", "SoftwareComponent")
                        .WithMany("ConfigurationEntries")
                        .HasForeignKey("SoftwareComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BvHardwareComputer");

                    b.Navigation("SoftwareComponent");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbHardwareComputer", b =>
                {
                    b.HasOne("MECWeb.DbModels.Workflow.DbWorkflow", "Workflow")
                        .WithMany("HardwareComputers")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbHardwareField", b =>
                {
                    b.HasOne("MECWeb.DbModels.Workflow.DbHardwareComputer", "HardwareComputer")
                        .WithMany("HardwareFields")
                        .HasForeignKey("HardwareComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HardwareComputer");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbSoftwareComponent", b =>
                {
                    b.HasOne("MECWeb.DbModels.Workflow.DbHardwareComputer", "HardwareComputer")
                        .WithMany("SoftwareComponents")
                        .HasForeignKey("HardwareComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HardwareComputer");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbWorkflow", b =>
                {
                    b.HasOne("MECWeb.DbModels.Project.DbProject", "Project")
                        .WithMany("Workflows")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MECWeb.DbModels.Project.DbProject", b =>
                {
                    b.Navigation("Machines");

                    b.Navigation("TranslateProjects");

                    b.Navigation("UserProjectFavorites");

                    b.Navigation("UserProjects");

                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("MECWeb.DbModels.Translate.DbTranslateDictionary", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("MECWeb.DbModels.Translate.DbTranslateEntry", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("MECWeb.DbModels.User.DbUser", b =>
                {
                    b.Navigation("UserProjectFavorites");

                    b.Navigation("UserProjects");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbBvHardwareComputer", b =>
                {
                    b.Navigation("HardwareComponents");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbHardwareComputer", b =>
                {
                    b.Navigation("HardwareFields");

                    b.Navigation("SoftwareComponents");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbSoftwareComponent", b =>
                {
                    b.Navigation("ConfigurationEntries");
                });

            modelBuilder.Entity("MECWeb.DbModels.Workflow.DbWorkflow", b =>
                {
                    b.Navigation("HardwareComputers");
                });
#pragma warning restore 612, 618
        }
    }
}
